name: "SummarAIzeHub"
description: "Automatically summarize long GitHub issues when /summarize-issue is commented"
inputs:
  PERSONAL_ACCESS_TOKEN:
    description: "GitHub token to authenticate and interact with the GitHub API"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key to access the GPT-powered summarizer"
    required: true
  prompt_template_path:
    description: "Path to the prompt template file"
    required: false
    default: "templates/prompt_template.txt"
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: zerebom/SummarAIzeHub@main

    - name: Install Poetry
      shell: bash
      run: |
        pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        # cache: poetry
        # cache-dependency-path: poetry.lock
    - name: Install Python library
      run: |
        poetry install --no-interaction
      shell: bash

    - name: Run summarizer
      shell: bash
      run: poetry run python src/main.py "${{ github.event.repository.full_name }}" "${{ github.event.issue.number }}" "${{ github.event.comment.id }}" "${{ inputs.PERSONAL_ACCESS_TOKEN }}"
      env:
        PERSONAL_ACCESS_TOKEN: ${{ inputs.PERSONAL_ACCESS_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
